<Project Sdk="Dalamud.NET.Sdk/15.0.0">

  <PropertyGroup>
    <Version>0.1.0</Version>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <Platforms>x64</Platforms>
    <ProduceReferenceAssembly>false</ProduceReferenceAssembly>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <OutputPath>$(MSBuildProjectDirectory)\..\build\EmoteSplitter</OutputPath>
  </PropertyGroup>

  <PropertyGroup>
    <Author>Tildemancer</Author>
    <Name>Emote Splitter</Name>
    <Punchline>Type past the chat limit.</Punchline>
    <Description>Type past the chat limit. Long messages are split and sent in order.</Description>
    <Tags>Social;Utility;Roleplay</Tags>
  </PropertyGroup>

</Project>
